name: Test yaml file

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display local environment variable
        env:
          TEST_SECRETS: ${{ secrets.test_keys }}
        run: |
          echo Variables: $TEST_SECRETS 
          